- name: Matt's Playbook
  hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    dev: "{{ lookup('env', 'HOME') }}/dev"
    config: "{{ lookup('env', 'HOME') }}/.config"
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/fish.yml
