- name: adding wezterm sources
  shell: |
    curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
    echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
    sudo apt update

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "curl", "golang", "i3", "nvidia-settings", "wezterm", "neovim", "tmux", "fzf", "xclip", "tldr", "ripgrep", "fish", "eza" ]
#
# - name: Install rustup
#   shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
#   become_user: mattc
