- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: neovim config
  ansible.builtin.git:
    repo: 'git@github.com:mat2cc/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    update: yes
    accept_hostkey: yes
    version: master

- name: link dotfies
  shell: stow .
  args:
    chdir: ~/.dotfiles
